<?php
	
	$PREFIX = "../../../";
	
	$PATH_CONSTANTS = "globals/php/path_constants.php";
	
	$PREFIXED_PATH_CONSTANTS = $PREFIX.$PATH_CONSTANTS;
	require_once $PREFIXED_PATH_CONSTANTS;
	
	$PREFIXED_TAB_TITLE_PATH = $PREFIX.$TAB_TITLE_PATH;
	$PREFIXED_PDO_PATH = $PREFIX.$PDO_PATH;
	$PREFIXED_TABLE_IDENTIFIERS_AND_STATEMENTS_PATH = $PREFIX.$TABLE_IDENTIFIERS_AND_STATEMENTS_PATH;
	$PREFIXED_GLOBAL_JS_HELP_PATH = $PREFIX.$GLOBAL_JS_HELP_PATH;

	$REDIRECT_TO_INDEX = $PREFIX.'index.php';
?>
